### ISSUE TITLE
Flex-direction utils

### ISSUE THREAD

**Issue by woodcox** [BinaryMoon/ElementalCSS#5]
Hi, this looks like a really nice headless css library. 

I was reading through the dist css and noticed you have two utility classes for flex-direction that do the same job:

```css
.flex-row {
	flex-direction: row;
}
.flex-col {
	flex-direction: column;
}
.flex-d-c {
	flex-direction: column;
}
.flex-d-r {
	flex-direction: row;
}
```

I wasn’t sure if this was an error or intentional when looking at the `_flex.scss`?

Otherwise, on first read it looks great 👍. I really like the clear and concise utility class names.
